In [28]:
print("hello world")

hello world


In [29]:
print("hi again")

hi again


# DSR Day 1

+ first
+ second

** bold **

_italic_

In [32]:
a = 3
b = 2*a
type(b)

int

In [34]:
print(b)

6


In [36]:
b = "hello"

In [41]:
a = 3
b = 2
a/float(b)

1.5

In [59]:
colors = ['red', 'blue', 'green', 'black', 'white']
colors[2]

'green'

In [47]:
colors[2:4]

['green', 'black']

In [51]:
colors.append('pink')
colors

['red', 'blue', 'green', 'black', 'white', 'pink', 'pink', 'pink']

In [58]:
colors.pop()
colors

['red', 'blue', 'green', 'black']

In [62]:
rcolors = colors[::-1]
rcolors

['white', 'black', 'green', 'blue', 'red']

In [65]:
sorted_colors = sorted(colors)
sorted_colors

['black', 'blue', 'green', 'red', 'white']

In [66]:
colors.extend('pink')

In [67]:
colors

['red', 'blue', 'green', 'black', 'white', 'p', 'i', 'n', 'k']

In [68]:
i = 5
'An integer: %i; a float: %f; another string: %s' % (i, 0.1, 'string')

'An integer: 5; a float: 0.100000; another string: string'

In [71]:
tel = {'emmanuelle': 5752, 'sebastian': 5578}
tel['francis'] = 7386

In [76]:
tel.keys()

dict_keys(['emmanuelle', 'sebastian', 'francis'])

In [77]:
tel.values()

dict_values([5752, 5578, 7386])

In [79]:
if 5 == 5:
    print("obvious!")

obvious!


In [82]:
a = 10
if a == 3:
    print('a = 3')
elif a == 5:
    print('a = 5')
else:
    print('a is not 3 nor 5')

a is not 3 nor 5


In [84]:
z = 1 + 1j
while abs(z) < 100:
    if z.imag == 0:
        break
    z = z**2 + 1
print(z)

(-134+352j)


In [85]:
vowels = 'aeiouy'

for i in 'powerful':
    if i in vowels:
        print(i)

o
e
u


In [87]:
message = "Hello how are you?"
for word in message.split():
    print(word)

Hello
how
are
you?


In [89]:
words = ('cool', 'powerful', 'readable')
for i in range(0, len(words)):
    print(i, words[i])

0 cool
1 powerful
2 readable


In [91]:
for index, item in enumerate(words):
    print(index, item)

0 cool
1 powerful
2 readable


In [154]:
i = 1
k = 1
while i < 10000:
    k = k * (4*i*i)/(4*i*i-1)
    i = i + 1
print(2*k)

3.141514110828136


#### Calculate Pi (short)

In [191]:
[a*k for k in [(4*i*i)/(4*i*i-1) for i in range(1,100000)]]
print(2*a)

3.1408069608284657


#### Calculate Pi (as a function)

In [192]:
def calculate_pi(precision=10000):
    """Calculates Pi"""
    [a*k for k in [(4*i*i)/(4*i*i-1) for i in range(1,precision)]]
    return 2*a

print(calculate_pi())

3.1408069608284657


#### Calculate Pi (with precision given explicitly)

In [185]:
i = 1
k = 1
while True:
    k = k * (4*i*i)/(4*i*i-1)
    i = i + 1
    if ((4*i*i)/(4*i*i-1)-1) < 0.0000000000001:
        break
print(2*k)

3.1415921567835725


In [204]:
def calc_fibonacci(no_of_terms):
    a = 0
    b = 1
    i = 0
    while i < no_of_terms:
        print(a)
        c = a + b
        a = b
        b = c

        i = i + 1

calc_fibonacci(10)

0
1
1
2
3
5
8
13
21
34


In [214]:
def calc_fibonacci(n):
    a, b = 0, 1
    for i in range(n):
        print(a)
        a, b = b, a + b
        
calc_fibonacci(10)

0
1
1
2
3
5
8
13
21
34


In [220]:
def fib_rec(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib_rec(n - 1) + fib_rec(n - 2)
    
for i in range(0,10):
    print(fib_rec(i))

0
1
1
2
3
5
8
13
21
34


#### Quicksort

In [278]:
def quicksort(array):
    less = []
    greater = []
    pivot = []
    if len(array) < 2:
        return array
    pivot.append(array.pop())
    for x in array:
        if x < pivot[0] + 1:
            less.append(x)
        else:
            greater.append(x)
    return quicksort(less) + pivot + quicksort(greater)

quicksort([10, 21, 2, 53, 5, 38])



[2, 5, 10, 21, 38, 53]

In [284]:
import numpy as np

In [285]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [286]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [290]:
dt = np.dtype([('age',np.int8)])

a = np.array([(10,),(20,),(30,)],dtype = dt)
print(a['age'])

[10 20 30]


In [292]:
student = np.dtype([('name', 'S20'), ('age', 'i1'), ('mark', 'f4')])
a = np.array([('abc', 21, 50), ('xyz', 23, 43)], dtype = student)
print(a)

[(b'abc', 21, 50.) (b'xyz', 23, 43.)]


In [304]:
a = np.array([[1,2,3],[4,5,6]]) 
print(a.shape)
a.shape = (1, 6)
print(a)

(2, 3)
[[1 2 3 4 5 6]]


In [323]:
a = np.arange(24)
b = a.reshape(2,3,4)
x = np.array([1,2,3,4,5], dtype = np.int8)
print(x.itemsize)

1


In [332]:
x = np.empty([3,2], dtype = np.int8)
print(x)

[[ 40  40]
 [115 101]
 [108 102]]


In [340]:
x = np.zeros([64, 64], dtype = int)
print(x)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [358]:
x = (1,2,3) 
a = np.asarray(x) 
print(a)

a = np.fromiter(range(5), int)
print(a)

a = np.arange(0, 10, 2)
print(a)

a = np.linspace(0, 50, 10, dtype = int)
print(a)

a = np.arange(10)
print(a[2:9])

[1 2 3]
[0 1 2 3 4]
[0 2 4 6 8]
[ 0  5 11 16 22 27 33 38 44 50]
[2 3 4 5 6 7 8]


In [365]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 

print('Our array is:')
print(a) 
print('\n')

# this returns array of items in the second column 
print('The items in the second column are:')  
print(a[...,1])
print('\n')

# Now we will slice all items from the second row 
print('The items in the second row are:')
print(a[1,...])
print('\n')

# Now we will slice all items from column 1 onwards 
print('The first two items of the first two rows are:') 
print(a[:2,:2])
print(a[2,2])

Our array is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


The items in the second column are:
[2 5 8]


The items in the second row are:
[4 5 6]


The first two items of the first two rows are:
[[1 2]
 [4 5]]
9


In [375]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
print('Our array is:')
print(x)
print('\n')

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 

print('The corner elements of this array are:')
print(y)
print('\n')

print('The element in position 3,2 is:')
print(x[3,2])
print('\n')

print('The elements larger than 5 are:')
print(x[x>5])

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The corner elements of this array are:
[[ 0  2]
 [ 9 11]]


The element in position 3,2 is:
11


The elements larger than 5 are:
[ 6  7  8  9 10 11]


In [376]:
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b
print(c)

[ 10  40  90 160]


In [381]:
a = np.arange(0,60,5)
for i in np.nditer(a):
    print(i)

0
5
10
15
20
25
30
35
40
45
50
55


In [383]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
print('Original array is:')
print(a)
print('\n')

for x in np.nditer(a, op_flags = ['readwrite']):
   x[...] = x**3
print('Modified array is:')
print(a)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
[[     0    125   1000   3375]
 [  8000  15625  27000  42875]
 [ 64000  91125 125000 166375]]


In [386]:
a = np.array([[1,2],[3,4]]) 

print('First array:')
print(a)
print('\n')
b = np.array([[5,6],[7,8]]) 

print('Second array:')
print(b)
print('\n')
# both the arrays are of same dimensions 

print('Joining the two arrays along axis 0:')
print(np.concatenate((a,b), axis = 0))
print('\n')

print('Joining the two arrays along axis 1:')
print(np.concatenate((a,b), axis = 1))

First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]


Joining the two arrays along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Joining the two arrays along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [408]:
x = np.empty([3,2], dtype = int)
y = x = np.empty([3,2], dtype = int)
print(x)
print('\n')
print(y)
print('\n')
print(np.concatenate((x,y), axis = 1))

[[552205024       469]
 [659202336       469]
 [641449032       469]]


[[552205024       469]
 [659202336       469]
 [641449032       469]]


[[552205024       469 552205024       469]
 [659202336       469 659202336       469]
 [641449032       469 641449032       469]]


In [411]:
a = np.arange(12).reshape(3,4)
print(a)
print('\n')
np.transpose(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]




array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])